# Customer Segmentation - Preprocessing and Training

This notebook will be used to prepare the data set for clsutering and to create a baseline clustering model. All data cleaning was done in [this](https://github.com/NickD-Dean/Springboard/blob/ce7358bfc84ceee14d287000eb132e8ff06a944b/Capstone%20Project%203/Code/03%20-%20Customer%20Segmentation%20Data%20Wrangling.ipynb) notebook, and exploratory analysis can be found [here](https://github.com/NickD-Dean/Springboard/blob/ce7358bfc84ceee14d287000eb132e8ff06a944b/Capstone%20Project%203/Code/04%20-%20Exploratory%20Data%20Analysis.ipynb)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples
import matplotlib.cm as cm
from sklearn.decomposition import PCA
import matplotlib.colors

# Setup Seaborn
sns.set_style("whitegrid")
sns.set_context("poster")

In [6]:
data = pd.read_csv('../Data/Cleaned_Customer_Data', index_col = 0)

In [7]:
data.head()

,Age,Marital_status,Income,Homeowner_status,Household_comp,Household_size,Kids,CampaignsRedeemed,CampaignsSent,Percent_CampaignRedeemed,...,Num_stores_visited,Most_freq_store,Most_freq_time,First_active_day,Last_active_day,Recency,Frequency,Monetary,Avg_trips_week,Avg_shopping_lag
1,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,2,8,0.25,...,2,436.0,1456.0,51,706,5,0.120956,4330.16,1.264706,7.705882
2,0,0,0,0,0,0,0,0,1,0.00,...,5,401.0,1904.0,103,668,43,0.063291,1954.34,1.285714,12.840909
3,0,0,0,0,0,0,0,0,3,0.00,...,3,401.0,1549.0,113,703,8,0.066104,2653.21,1.270270,12.826087
4,0,0,0,0,0,0,0,0,1,0.00,...,6,298.0,1452.0,104,627,84,0.042194,1200.11,1.153846,18.034483
5,0,0,0,0,0,0,0,0,0,0.00,...,3,374.0,1540.0,85,703,8,0.056259,779.06,1.481481,15.846154